# Generated by Django 3.0.6 on 2020-05-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200531_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='next_quest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Questions'),
        ),
    ]
